FROM nginx:latest
# LABEL Name=devopsproject.uiapp Version=0.0.1
# RUN apt-get -y update && apt-get install -y fortunes
# CMD ["sh", "-c", "/usr/games/fortune -a | cowsay"]
COPY . /usr/share/nginx/html 
