services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - music-network

  apigateway:
    build:
      context: .
      dockerfile: Services.ApiGateway/Dockerfile
    image: apigateway:dev
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - music-network

  identityservices:
    build:
      context: .
      dockerfile: IdentityService.Web-API/Dockerfile
    image: identityservice.web-api:dev
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - music-network

  musicservices:
    build:
      context: .
      dockerfile: MusicService.Web-API/Dockerfile
    image: musicservice.web-api:dev
    ports:
       - "5002:8080"
    environment:
       - ASPNETCORE_ENVIRONMENT=Production
    networks:
       - music-network

  uiapp:
    build:
      context: .
      dockerfile: devopsproject.uiapp/Dockerfile
    image: musicuiapp:dev
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - music-network

networks:
  music-network: