version: '3.8'

services:
  app1:
    image: identityservice.web-api:dev
    build:
      context: .
      dockerfile: Services/IdentityServices/IdentityService.Web-API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  app2:
    image: musicservice.web-api:dev
    build:
      context: .
      dockerfile: Services/MusicServices/MusicService.Web-API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  app3:
    image: apigateway:dev
    build:
      context: .
      dockerfile: Services/Services.ApiGateway/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  app4:
    image: musicuiapp:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production